# Generated by Django 3.0.8 on 2023-08-14 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('post_image', models.TextField(max_length=2000)),
                ('diff', models.IntegerField(choices=[(1, 'light'), (2, 'middle'), (3, 'heavy')])),
                ('bookmark', models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(to='account.Hashtag')),
                ('post_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostSec',
            fields=[
                ('sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('sec_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_post', to='post.Post')),
            ],
        ),
    ]
