# Generated by Django 3.0.8 on 2023-08-14 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('line', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('item1', models.CharField(max_length=400)),
                ('item2', models.CharField(max_length=400)),
                ('item3', models.CharField(max_length=400)),
                ('is_done', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('done_date', models.DateField(default=None, null=True)),
                ('vote_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_line', to='line.Line')),
                ('vote_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_post', to='post.Post')),
                ('vote_postsec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_postsec', to='post.PostSec')),
                ('vote_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotePer',
            fields=[
                ('voteper_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(choices=[(1, '10대'), (2, '20대'), (3, '30대'), (4, '40대'), (5, '50대 이상')], null=True)),
                ('select', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('voteper_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteper_user', to=settings.AUTH_USER_MODEL)),
                ('voteper_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteper_vote', to='vote.Vote')),
            ],
        ),
    ]
